git lfs

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,6 +1,13 @@
 #!/usr/bin/env sh
 set -ue
 
+if [ -f .gitatributes ] && grep -qE '\sfilter=lfs(\s|$)' .gitattributes
+then
+    # snippet from git lfs update --manual
+    command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
+    git lfs pre-push "$@"
+fi
+
 if [ -z "${HOOKS_DIR-}" ]
 then
     echo 1>&2 "ERROR: HOOKS_DIR is not set. Please re–install @saji/git-hooks."
